name: mutcaller
version: "0.1"
author: scott furlan <furlan_scott@hotmail.com>
about: call mutations in single cell genomic data
args:
    - input_bam:
        long: ibam
        short: i
        takes_value: true
        required: true
        help: input bam
    - threads:
        long: threads
        short: t
        takes_value: true
        required: false
        help: threads
    - split:
        long: split
        short: s
        takes_value: true
        required: false
        help: split read name by