name: mutcaller
version: "0.1"
author: scott furlan <furlan_scott@hotmail.com>
about: call mutations in single cell genomic data
args:
    - input_bam:
        long: ibam
        short: i
        takes_value: true
        required: true
        help: input bam
    - threads:
        long: threads
        short: t
        takes_value: true
        required: false
        help: threads
    - split:
        long: split
        short: s
        takes_value: true
        required: false
        help: split read name by
    - no_header:
        long: no_header
        short: nh
        takes_value: false
        required: false
        help: include header in output
    - joiner:
        long: joiner
        short: j
        takes_value: true
        required: false
        help: character to rejoin read name with barcode
    - cb_len:
        long: cb_len
        short: c
        takes_value: true
        required: false
        help: cell barcode length
    - umi_len:
        long: umi_len
        short: u
        takes_value: true
        required: false
        help: cell barcode length